import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:just_audio_background/just_audio_background.dart';
import 'package:audio_service/audio_service.dart';

import 'core/constants.dart';
import 'core/di.dart';
import 'core/theme/dark_theme.dart';
import 'core/theme/light_theme.dart';
import 'presentation/screens/home/home_screen.dart';
import 'presentation/screens/search/search_screen.dart';
import 'presentation/screens/library/library_screen.dart';
import 'presentation/screens/playlist_detail/playlist_detail_screen.dart';
import 'presentation/screens/now_playing/now_playing_screen.dart';
import 'presentation/screens/settings/settings_screen.dart';
import 'presentation/providers/settings_controller.dart';
import 'presentation/providers/queue_controller.dart';
import 'presentation/providers/library_controller.dart';
import 'presentation/widgets/player_bar.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Hive
  await Hive.initFlutter();
  
  // Register Hive adapters (generated by build_runner)
  // Hive.registerAdapter(TrackAdapter());
  // Hive.registerAdapter(PlaylistAdapter());
  // Hive.registerAdapter(ArtistAdapter());
  
  // Open boxes
  await Hive.openBox(AppConstants.boxTracks);
  await Hive.openBox(AppConstants.boxPlaylists);
  await Hive.openBox(AppConstants.boxLiked);
  await Hive.openBox(AppConstants.boxQueue);
  await Hive.openBox(AppConstants.boxHistory);
  await Hive.openBox(AppConstants.boxSettings);
  
  // Initialize JustAudioBackground for background audio
  await JustAudioBackground.init(
    androidNotificationChannelId: 'com.cheater345.mpltyop.channel.audio',
    androidNotificationChannelName: 'MPLTYOP Audio',
    androidNotificationOngoing: true,
  );
  
  // Initialize AudioService
  await AudioService.init(
    builder: () => PlaybackService(),
    config: const AudioServiceConfig(
      androidNotificationChannelId: 'com.cheater345.mpltyop.channel.audio',
      androidNotificationChannelName: 'MPLTYOP Audio',
      androidNotificationOngoing: true,
      androidStopForegroundOnPause: true,
    ),
  );

  runApp(const ProviderScope(child: MPLTYOPApp()));
}

class MPLTYOPApp extends ConsumerWidget {
  const MPLTYOPApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final settings = ref.watch(settingsControllerProvider);
    
    return MaterialApp(
      title: AppConstants.appName,
      debugShowCheckedModeBanner: false,
      theme: lightTheme,
      darkTheme: darkTheme,
      themeMode: settings.themeMode,
      home: const MainNavigation(),
      routes: {
        '/now-playing': (context) => const NowPlayingScreen(),
        '/playlist': (context) => const PlaylistDetailScreen(),
        '/settings': (context) => const SettingsScreen(),
      },
    );
  }
}

class MainNavigation extends ConsumerStatefulWidget {
  const MainNavigation({super.key});

  @override
  ConsumerState<MainNavigation> createState() => _MainNavigationState();
}

class _MainNavigationState extends ConsumerState<MainNavigation> {
  int _selectedIndex = 0;
  final _screens = [
    const HomeScreen(),
    const SearchScreen(),
    const LibraryScreen(),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Row(
        children: [
          NavigationRail(
            selectedIndex: _selectedIndex,
            onDestinationSelected: (index) => setState(() => _selectedIndex = index),
            labelType: NavigationRailLabelType.all,
            destinations: const [
              NavigationRailDestination(
                icon: Icon(Icons.home_outlined),
                selectedIcon: Icon(Icons.home),
                label: Text('Home'),
              ),
              NavigationRailDestination(
                icon: Icon(Icons.search_outlined),
                selectedIcon: Icon(Icons.search),
                label: Text('Search'),
              ),
              NavigationRailDestination(
                icon: Icon(Icons.library_music_outlined),
                selectedIcon: Icon(Icons.library_music),
                label: Text('Library'),
              ),
            ],
          ),
          const VerticalDivider(thickness: 1, width: 1),
          Expanded(
            child: _screens[_selectedIndex],
          ),
        ],
      ),
      bottomNavigationBar: const PlayerBar(),
    );
  }
}